### ISSUE TITLE
Access/Refresh token missing

### ISSUE THREAD

**Issue by jasonbrice** [ringcentral/ringcentral-js#100]
When loading the login.html from the demo, Platform.js throws an error: 

login.html:148 Error: Refresh token is missing
    at Platform.<anonymous> (Platform.js:402)

Troubleshooting steps I've performed so far: 
 * verified that I'm using the latest ringcentral.js as of 9/11/2018
 * verified that the Client ID and Client Secret match my sandbox application, and that they are stored in local storage
 * granted all possible permissions in my app in the sandbox environment
 * all libraries and depdendncies are loading normally, there are no errors in the console before the one described above

**Comment by kirill-konshin** [comment]
That's normal, it tries to log you in using refresh token, fails to find one and throws the error. Just authenticate and you won't see the error.
