### ISSUE TITLE
Typings and/or reimplement in Typescript

### ISSUE THREAD

**Issue by julien-c** [ringcentral/ringcentral-js#105]
Hi guys,

If I understand https://github.com/ringcentral/ringcentral-js/pull/102 correctly seems like you are in the process of rewriting to TS. Which is awesome!

In the meantime, any way you could push Type definition files to the master build on npm (I'm assuming you might be able to generate the typings from the OpenAPI definition file?)

Let me know if this is doable! Looking forward to the reimplementation in any case.

**Comment by kirill-konshin** [comment]
You can use published alphas, they are fairly stable, although interfaces may change slightly: namespaces and naming mostly.

There are no plans to create definitions for older versions as it's a lot of effort and we already have a new version... feel free to submit a PR if you'd like.
