### ISSUE TITLE
Provide CDN version of RingCentral JS SDK

### ISSUE THREAD

**Issue by bdeanindy** [ringcentral/ringcentral-js#11]
Would be nice if there were CDN (such as cloudflare, or another CDN) versions of the RingCentral JS SDK that contained links for:
- Unminified version
- Minified version

**Comment by grokify** [comment]
[CDNJS](https://cdnjs.com/) which runs on CloudFlare is a good option as are others that may be easier to use.

**Comment by tylerlong** [comment]
Another option is https://rawgit.com/, it provides CDN for free for all the public repositories hosted on GitHub.

For current version 2.0.5:
Unminified version: https://cdn.rawgit.com/ringcentral/ringcentral-js/2.0.5/build/ringcentral.js
Minified version: https://cdn.rawgit.com/ringcentral/ringcentral-js/2.0.5/build/ringcentral.min.js

**Comment by kirill-konshin** [comment]
Good to know, thank you
