### ISSUE TITLE
Change the AppKey and AppSecret to clientId and clientSecret

### ISSUE THREAD

**Issue by dibyenduroy** [ringcentral/ringcentral-js#113]
Currently, the SDK code shows AppKey and AppSecret but as per the latest changes it should be updated to  clientId and clientSecret so that the code works.

**Comment by grokify** [comment]
Here's the page that needs to be updated:

https://github.com/ringcentral/ringcentral-js/blob/1ca3267452bbf40a7c83907a39efbdd25bb4fc53/sdk/README.md

Code using `appKey` and `appSecret` exists 3 times on the page.

```js
import {SDK} from "@ringcentral/sdk";
// op
const SDK = require('@ringcentral/sdk').SDK;

const rcsdk = new SDK({
    server: SDK.server.sandbox,
    appKey: 'yourAppKey',
    appSecret: 'yourAppSecret',
    redirectUri: '' // optional, but is required for Implicit Grant and Authorization Code OAuth Flows (see below)
});
```

**Comment by kirill-konshin** [comment]
Fixed
