### ISSUE TITLE
Some feedbacks for version 4.x

### ISSUE THREAD

**Issue by tylerlong** [ringcentral/ringcentral-js#116]
Recently I got some feedbacks from developers about Version 4.x. I summary it here:

## appKey, appSecret renaming

So `appKey` has been renamed to `clientId` and `appSecret` has been renamed to `clientSecret`.

This breaks majority of the existing apps. 

I am thinking maybe we can support both for a while and mark former as deprecated.

## apiResponse.json() method changed from sync style to async style ?

Not 100% sure but if it is true, it will break most apps.

## Reference error

One developer reported that he got reference error after referencing ringcentral.js & ringcentral-subscription.js  I will follow up.

**Comment by dougroutledge** [comment]
Easy enough to rename appKey, the rest however, seems to break about every part of  every app.  Where are the examples of how to do platform.get etc with the 4.x release, as it would appear every use of the platform in every app will need to be recoded.

**Comment by kirill-konshin** [comment]
Here's the change log: https://github.com/ringcentral/ringcentral-js/blob/master/CHANGELOG.md

**Comment by dougroutledge** [comment]
Yeah that is already there, what is needed is updated code samples for login, platform calls, etc.

**Comment by SushilMallRC** [comment]
This issues does not require action , closing this issue.
