### ISSUE TITLE
Too abstract status information for RingOut

### ISSUE THREAD

**Issue by tylerlong** [ringcentral/ringcentral-js#12]
I followed the instructions here: https://github.com/ringcentral/ringcentral-js#making-telephony-calls

And it did work for some telephone numbers. But for some other numbers, there were issues. The status information  is:

```
{ uri: 'https://platform.ringcentral.com/restapi/v1.0/account/37439510/extension/850957020/ringout/10',
  id: 10,
  status: 
   { callStatus: 'CannotReach',
     callerStatus: 'GenericError',
     calleeStatus: 'Success' } }
```

I think the information above is too simple and abstract, and I have no idea what happened.

I check this endpioint `/account/~/extension/~/call-log`, it seems that the RingOut result is `IP Phone Offline`

Maybe this issue belongs to the REST API team, feel free to close it.

**Comment by kirill-konshin** [comment]
This issue should be reported to API team, that's right. I've forwarded your request to them.
