### ISSUE TITLE
When Instantiating SDK, allow option to set handleRateLimit to true across all requests

### ISSUE THREAD

**Issue by Brutalbeard** [ringcentral/ringcentral-js#122]
Would be a nice convenience feature. 

`const rcsdk = new SDK({
clientId: "",
clientSecret: "",
handleRateLimit: true
})
`

It *almost* looks like this can be done currently, by passing down a defaultRequestInit all the way down to the new Client, but I haven't been able to get it to work just yet.

**Comment by SushilMallRC** [comment]
@Brutalbeard this issue is already merged with PR https://github.com/ringcentral/ringcentral-js/pull/123 , for now, I'm closing this issue please feel free to reopen or create a new One.
