### ISSUE TITLE
Cannot find name 'Response'

### ISSUE THREAD

**Issue by tylerlong** [ringcentral/ringcentral-js#137]
I am using SDK v4 in a TypeScript project. When I compile  the project I got the following error:

```
node_modules/@ringcentral/sdk/lib/SDK.d.ts:26:45 - error TS2304: Cannot find name 'Response'.

26     send: (options: SendOptions) => Promise<Response>;
```

I checked the source code of https://github.com/ringcentral/ringcentral-js/blob/master/sdk/src/SDK.ts

I find that `Response` is not defined anywhere. Or it is defined somewhere but not imported into that file.

**Comment by kirill-konshin** [comment]
Never had such an issue. This is standard class, part of browser fetch API.

**Comment by tylerlong** [comment]
Browser has it whie Node doesn't.

```
node
Welcome to Node.js v13.12.0.
Type ".help" for more information.
> Response
Uncaught ReferenceError: Response is not defined
> 
```

**Comment by kirill-konshin** [comment]
Use isomorphic unfetch or similar library. Still make sure TS libs are properly defined.

**Comment by tylerlong** [comment]
The current issue is the SDK doesn't compile in a Node.js TypeScript project.

So if a node.js project use RC SDK V4, it needs to use "isomorphic unfetch" to make HTTP calls directly?

**Comment by tylerlong** [comment]
OK, here is the workaround: add `"lib": ["DOM"]` to tsconfig.json `compilerOptions`.

In theory my app doesn't need DOM because it is a Node.js app. This workaround is just to fool the TypeScript compiler.
