### ISSUE TITLE
@ringcentral/sdk-utils not in npm registry

### ISSUE THREAD

**Issue by mariansurdu112** [ringcentral/ringcentral-js#143]
@ringcentral/sdk-utils not in npm registry

What to do?

**Comment by kirill-konshin** [comment]
What's the use case? You normally don't need this package, it's used for test/build configs.

**Comment by mariansurdu112** [comment]
I just cloned the repository and run npm install. And i received this error. The package is in package.json list.
By the way, did you integrate ringcentral with an react application?

**Comment by kirill-konshin** [comment]
Yes, there's a dedicated package for that. You should run `npm install` in the root of the cloned repo, `lerna` will link all packages. May I know what are you trying to do and why you cloned the repo? It's not needed if you only need to use it, not contribute.

**Comment by mariansurdu112** [comment]
I just want to integrate ringcentral into an blank react application, to have possibility to make/receive calls

**Comment by kirill-konshin** [comment]
Just follow the readme then, you don’t need to clone the repo.
