### ISSUE TITLE
Unhandled Rejection (Error): Unable to parse response

### ISSUE THREAD

**Issue by mariansurdu112** [ringcentral/ringcentral-js#144]
Hi,
On react application i receive: **Unable to parse response**.

I'm using `const login = () => window.location.assign(loginUrl({ implicit:false,usePKCE: true }));` .

For implicit: true, i receive: **Unhandled Rejection (Error): The client is unauthorized for the required grant type: [IMPLICIT]**

All errrors come from parseRedirect(hash) method.

Any help will be appreciated

**Comment by kirill-konshin** [comment]
Please use https://developers.ringcentral.com/support.html
