### ISSUE TITLE
Cache clean issue with prefix

### ISSUE THREAD

**Issue by embbnux** [ringcentral/ringcentral-js#157]
In current version, sdk clean cache with prefix. With default prefix 'rc-', it may remove storage that doesn't belongs to sdk. We need to only clean keys used in SDK.

https://github.com/ringcentral/ringcentral-js/blob/master/sdk/src/core/Cache.ts#L54

**Comment by kirill-konshin** [comment]
The whole point of SDK cache is to wipe everything that's potentially private if user logs out. If you want to keep something — just use LS directly.
