### ISSUE TITLE
Improve error reporting when missing API Keys

### ISSUE THREAD

**Issue by bdeanindy** [ringcentral/ringcentral-js#16]
If the API keys are missing while instantiating the SDK, you just receive a 400 Bad Request with Invalid credentials message.

It would be better if the SDK would catch this earlier (before it gets sent to the `request` module dependency) and notify the developer of either missing appKey or missing appSecret.

**Comment by kirill-konshin** [comment]
I don't think so. API will provide an error, there's no need to capture it earlier.
