### ISSUE TITLE
Add packages lock file in this project

### ISSUE THREAD

**Issue by embbnux** [ringcentral/ringcentral-js#170]
Currently we don't have packages lock file in git repo. 

CI may fail to work if some sub dependencies does't have downward compatibility.

**Comment by SushilMallRC** [comment]
@embbnux [package-lock.json](https://github.com/ringcentral/ringcentral-js/blob/master/package-lock.json) is now available in the repo, If you have additional feedback, please don't hesitate to reopen this issue or create a new one.
Closing this issue now.
