### ISSUE TITLE
3 Legged + PKCE with top frame fails 

### ISSUE THREAD

**Issue by nerdchacha** [ringcentral/ringcentral-js#171]
When using 3 legged oauth and using the top frame we suggest the user do the following on the redirect page

> Your application needs to have a special landing page to handle OAuth Redirect URI. On this page you need to resume the flow:
> 
> var loginOptions = rcsdk.parseLoginRedirect(window.location.hash || window.location.search);
> rcsdk.login(loginOptions).then(...);

**Assuming the user has 2 pages, login.html and redirect.html**

1. The login URL is generated in index.html by doing the following
```
var loginUrl = rcsdk.loginUrl({ usePKCE: true });
window.location.assign(loginUrl);
```
2. User is taken to the RingCentral login page.
3. On successful login, the user is redirected to the redirect.html page with the code (considering we are not using implicit flow)
3. The redirect.html page expects users to call 
```
var loginOptions = rcsdk.parseLoginRedirect(window.location.hash || window.location.search);
rcsdk.login(loginOptions).then(...);
```
4. Since the redirect.html is a different page, It will make a fresh instance of the SDK
5. The login method fill fail since usePKCE is set to true and SDK will try to attach code_verifier with the token request
6. Since the redirect.html page has a fresh instance of the SDK, it will not get the code_verifier generated on the `login()`call, and login will fail

**Comment by tylerlong** [comment]
Two options:

1. Do not redirect, use a popup window to let user login. It's the default implementation in the sdk: https://github.com/ringcentral/ringcentral-js/blob/eb71da9548d7bfbb588428f9b4eef8aa1a120c63/sdk/src/platform/Platform.ts#L367-L373
2. If page redirects, you need to first save `code_verifier` into cookie/localstorage...etc. Otherwise just like you said it won't work.

**Comment by embbnux** [comment]
Hi @nerdchacha For PKCE with redirect, you need to save `code_verifier` in your side before redirecting:
```js
var loginUrl = rcsdk.loginUrl({ usePKCE: true });
var codeVerifier = rcsdk.platform().codeVerifier;
localStorage.setItem('codeVerifier', codeVerifier);
window.location.assign(loginUrl);
```
After redirect:

```js
var loginOptions = rcsdk.parseLoginRedirect(window.location.hash || window.location.search);
loginOptions["code_verifier"] = localStorage.getItem('codeVerifier');
rcsdk.login(loginOptions).then(...);
```

**Comment by nerdchacha** [comment]
Thanks
Creating a PR to update this in the docs
