### ISSUE TITLE
Security vulnerability

### ISSUE THREAD

**Issue by zucatti** [ringcentral/ringcentral-js#174]
The module relies on node-fetch < 2.6.7 which is known as vulnerable. Please upgrade to the latest version of node-fetch
node-fetch  <2.6.7
Severity: high
node-fetch is vulnerable to Exposure of Sensitive Information to an Unauthorized Actor - https://github.com/advisories/GHSA-r683-j2x4-v87g

**Comment by suyashjoshi** [comment]
Thanks @zucatti for reporting this security concern. Let us take a look at it and try to resolve this asap.

**Comment by suyashjoshi** [comment]
Fix has been merged

**Comment by embbnux** [comment]
released with v4.7.2
