### ISSUE TITLE
"Invalid client id" error when refreshing token

### ISSUE THREAD

**Issue by byrnereese** [ringcentral/ringcentral-js#182]
A developer is migrating to auth code with PKCE for all their API calls. They are using the Javascript SDK and noticed a problem. When they invoke `platform.refresh()` to get a new auth token, they are getting an error regarding an invalid client iD. It appears the SDK is encoding an Authorization header with a client ID and no secret. Which is to be expected for some API calls in the Auth flow. When he composes a request to refresh a token without an auth header (via Postman) everything works.

**Comment by SushilMallRC** [comment]
Hi @byrnereese I tried to replicate this issue, 

1. Created a sample project.
2. Install @ringcentral/sdk 5.0.3 dependency
3. Created an index,js file, platform.login(jwt) -> Hit a RC API -> wait for 75 minutes -> platform.refresh() -> Hit RC API

It works perfectly to me.

<img width="1247" alt="Screenshot 2024-08-27 at 5 50 56 PM" src="https://github.com/user-attachments/assets/5a7ccd28-5ff9-49b6-9a4e-7ae5a6f59a4b">

**Comment by SushilMallRC** [comment]
This is not persist now, Closing this issue.
