### ISSUE TITLE
Support asynchronous externals.localStorage API

### ISSUE THREAD

**Issue by unadlib** [ringcentral/ringcentral-js#187]
We will run SDK in the Browser worker, but we can't use synchronous localStorage due to BOM restrictions.

From the implementation of `sdk/src/core/Cache.ts`, the internal API supports asynchronous, but `externals.localStorage` does not, is it considered to support asynchronous `externals.localStorage`?

**Comment by unadlib** [comment]
hi @kirill-konshin, will it be considered? I can submit PR for it.

**Comment by kirill-konshin** [comment]
@unadlib sure. `Cache` supports async, but it used to be sync, so some classes might still rely on presence of sync methods...

**Comment by unadlib** [comment]
> @unadlib sure. `Cache` supports async, but it used to be sync, so some classes might still rely on presence of sync methods...

Thanks for your reply, I will submit a PR to fix it.

**Comment by SushilMallRC** [comment]
Hi @kirill-konshin @unadlib  this issues is resolved with PR https://github.com/ringcentral/ringcentral-js/pull/265, Closing the issue now, please feel free to reopen or create new one if you face any issues.
