### ISSUE TITLE
platform is NOT singleton

### ISSUE THREAD

**Issue by tylerlong** [ringcentral/ringcentral-js#19]
https://github.com/ringcentral/ringcentral-js#get-the-platform-singleton

> ## Get the Platform singleton
> 
> ```js
> var platform = rcsdk.platform();
> ```
> 
> Now that you have your platform singleton and SDK has been configured with the correct server URL and API key, your
> application can log in so that it can access the features of the API.

https://en.wikipedia.org/wiki/Singleton_pattern

> In software engineering, the singleton pattern is a design pattern that restricts the instantiation of a class to one object. This is useful when exactly one object is needed to coordinate actions across the system.

It is possible to have multiple `platform` instances if user create multiple `rcsdk` instances. So it is not singleton, at least it's not the same singleton concept mentioned in design patterns.

I suggest that we update readme to avoid confusion.

**Comment by blak3r2** [comment]
This has caused a great deal of confusion for me... It's unclear to me whether or not it is a singleton though.

We have a multi-tenant, node-js, service that is monitoring multiple customers phone events... It seems that some things get cached in the singleton object and it's unclear as to whether that is causing issues.

**Comment by kirill-konshin** [comment]
It used to be a singleton back in the days, seems that documentation still has references like that in a couple of places.

**Comment by kirill-konshin** [comment]
PR is welcome

**Comment by blak3r2** [comment]
One more recommendation: the cachePrefix param which is referenced on the github readme should really be in the JS Developer Guide.  That would have saved me hours.

**Comment by kirill-konshin** [comment]
Right now documentation says:

> If you need to use 2 or more RingCentral accounts simultaneously, you need to create an instance of SDK for each account and provide some unique cachePrefix to SDK constructor (otherwise instances will share authentication).
