### ISSUE TITLE
Two login popups can open simultaneously

### ISSUE THREAD

**Issue by gauravsbagul** [ringcentral/ringcentral-js#191]
Hi,
I am having an issue when I try to log in, the login button is always enabled, and I can click on it again.
In this case, the second login popup opens if I click on the button again third login popup getting opened.
In an ideal case, I should get an error saying the popup is already open or the login process is already in progress—something like that.
 please refer to the Screenshots.
Is there any solution for this that I might have missed or do you still have to fix this bug?

![5082_Issues_ringcentral_ringcentral_js](https://user-images.githubusercontent.com/25247251/193601246-7f5bc881-bd49-4f2d-bfa1-48ad1e9dd410.png)

**Comment by SushilMallRC** [comment]
Hi @gauravsbagul Changes is merged witth PR https://github.com/ringcentral/ringcentral-js/pull/264 
closing this issue , feel free to reopen or create new one if you face any ieeus.
