### ISSUE TITLE
Do not specify default "Accept" header

### ISSUE THREAD

**Issue by tylerlong** [ringcentral/ringcentral-js#196]
https://github.com/ringcentral/ringcentral-js/blob/c7ba3e61ee3052ee42c8b0a5e3ff06862542d4d1/sdk/src/http/Client.ts#L132-L134

There is no need to specify it. Because the server knows what content type to return. There is no ambiguity.

And since we specify json as the accept type, binary downloading stops working recently (due to a recent change on server side)

**Comment by DaKingKong** [comment]
lines removed
