### ISSUE TITLE
Question about authUrl parameters

### ISSUE THREAD

**Issue by tylerlong** [ringcentral/ringcentral-js#20]
Code below is copied from https://github.com/ringcentral/ringcentral-js/blob/master/src/platform/Platform.js

``` javascript
    authUrl(options) {

        options = options || {};

        return this.createUrl(Platform._authorizeEndpoint + '?' + queryStringify({
                'response_type': 'code',
                'redirect_uri': options.redirectUri || '',
                'client_id': this._appKey,
                'state': options.state || '',
                'brand_id': options.brandId || '',
                'display': options.display || '',
                'prompt': options.prompt || ''
            }), {addServer: true})

    }
```

We can see from the code above that there are 7 query string parameters.

The documentation only mentioned 4: https://developer.ringcentral.com/api-docs/latest/index.html#!#AuthorizationCodeFlow

Where are the other three (`brand_id`,`display`,`prompt`) from and where to find documentaion about them?

@kirill-konshin 

By the way, code sample created by @grokify only contains 4 parameters (same as the documentation): https://github.com/grokify/ringcentral-oauth-demos/blob/master/python-bottle/app.py

``` python
params = (
        ('response_type', 'code'),
        ('redirect_uri', os.environ.get('RC_APP_REDIRECT_URL')),
        ('client_id', os.environ.get('RC_APP_KEY')),
        ('state', options['state'])
    )
```

**Comment by kirill-konshin** [comment]
- Display can alter the view of the login form — full, mobile friendly, etc
- BrandId is used to show branded login page
- Prompt is used for implicit grant, for example, could be none to skip all dialogs if user is already authorized
