### ISSUE TITLE
Missing login_hint param in loginUrl

### ISSUE THREAD

**Issue by panagiotis-charalampidis** [ringcentral/ringcentral-js#213]
https://github.com/ringcentral/ringcentral-js/blob/4.x/sdk/src/platform/Platform.ts

loginUrl method should also take loginHint as an argument and set the login_hint query parameter in the constructed url.

login_hint is a standard optional url parameter for oAuth2 authentication. 
https://auth0.com/docs/authenticate/identity-providers/pass-parameters-to-idps

The value passed pre-populates the email field in the RingCentral login form.

**Comment by SushilMallRC** [comment]
The changes have been made PR: https://github.com/ringcentral/ringcentral-js/pull/262, I'm closing this issue now feel free to reopen it if you have any doubts.
