### ISSUE TITLE
Need an option to disable token auto refresh

### ISSUE THREAD

**Issue by tylerlong** [ringcentral/ringcentral-js#220]
## The current behavior
For every API call, if the token expired, the SDK will auto refresh it and emit token fresh events.

## The expected behavior
Keep the current behavior the default one.
Add an option to disable auto refresh. Do not refresh even the token is expired. Just throw exception.
This way, developer gets more control over token management. They could proactively refresh token themselves instead of listening to token refresh events passively.

**Comment by SushilMallRC** [comment]
To disable the automatic token refresh feature, we can include the following code snippet in our application:
`platform.ensureLoggedIn = async () => null;`
This code effectively overrides the default token refresh mechanism, preventing the platform from automatically renewing the authentication token.
For a detailed explanation and further information, please refer to this article: [Disable Auto Token Refreshment](Refreshment]https://medium.com/@tylerlong/how-to-disable-auto-token-refreshment-for-ringcentral-javascript-sdk-461d7982ed35)
