### ISSUE TITLE
Build type error

### ISSUE THREAD

**Issue by lovemegowin** [ringcentral/ringcentral-js#223]
`src/lib/helper/http.ts:97:21 - error TS2322: Type '{ server: string | undefined; discoveryAutoInit: true; enableDiscovery: boolean; discoveryServer: string | undefined; clientId: string; clientSecret: string; cachePrefix: any; appName: string; appVersion: any; additionalUserAgent: string; }' is not assignable to type 'SDKOptions'.
  Object literal may only specify known properties, and 'additionalUserAgent' does not exist in type 'SDKOptions'.
`

`additionalUserAgent` property will incoming Platform construct by SDK https://github.com/ringcentral/ringcentral-js/blob/master/sdk/src/SDK.ts#L78 

but it not declared in `SDKOptions`

**Comment by embbnux** [comment]
It is weird, we declared in [PlatformOptions ](https://github.com/ringcentral/ringcentral-js/blob/master/sdk/src/platform/Platform.ts#L864). And `SDKOptions` extends `PlatformOptions`

**Comment by lovemegowin** [comment]
Sorry, I have just confirmed that this problem has been fixed in the latest version.
