### ISSUE TITLE
CHANGELOG missing for version 5

### ISSUE THREAD

**Issue by arecaps** [ringcentral/ringcentral-js#260]
I would like to update to use the latest version.
I would expect the CHANGELOG to show changes that need to be handled.
It seems to not have ben updated since version 4

**Comment by SushilMallRC** [comment]
Thank you for the feedback, I have raised PR https://github.com/ringcentral/ringcentral-js/pull/263 for the change.

**Comment by SushilMallRC** [comment]
Hi @arecaps ChangLog for version 5 has been merged with PR  https://github.com/ringcentral/ringcentral-js/pull/263

**Comment by SushilMallRC** [comment]
I'm closing this issue now, please feel free to reopen or create a new one if you have any further issues.
