### ISSUE TITLE
Remove Playwright as a postinstall step

### ISSUE THREAD

**Issue by ganderzz** [ringcentral/ringcentral-js#267]
Hey all,

We see periodic flakiness in CI builds because this package has a post-install script in the SDK that installs Playwright. This is not only a bad security practice, but is Playwright [being used in the codebase](https://github.com/search?q=repo%3Aringcentral%2Fringcentral-js%20playwright&type=code)? If so, it should be added as a `devDependency` so consuming apps don't download Playwright and subsequent dependencies (webkit, firefox, etc). 

https://github.com/ringcentral/ringcentral-js/blob/c86b8777fe34b2646dae79d9153352f74f2bbf23/sdk/package.json#L5

I am open to making the changes and creating a PR!

**Comment by tylerlong** [comment]
@embbnux It's introduced here: https://github.com/ringcentral/ringcentral-js/commit/5451c5a2687c79da3b1cb4bd5ed9ae6ef2e3a45c
We are not using playwright at all. Please remove the postinstall script. 
Thanks

**Comment by SushilMallRC** [comment]
Hi @ganderzz @tylerlong , Changes have been made in the PR  https://github.com/ringcentral/ringcentral-js/pull/268 and will update here once the new version is released. Thank you for pointing it out.

**Comment by SushilMallRC** [comment]
A new version, 5.0.3, has been released, which includes a fix for this issue. Closing this issue for now please feel free to reopen or create a new one. Thank You.

**Comment by ganderzz** [comment]
Thanks @SushilMallRC !
