### ISSUE TITLE
Auth refresh logic is causing an invalid token to exist

### ISSUE THREAD

**Issue by bdeanindy** [ringcentral/ringcentral-js#27]
My app operates just fine until the token nears expiration.

At the elapsed time ~ 59minutes after starting my app which uses the SDK to login and refers to the same instance for all subsequent requests in my long-running application, the token becomes invalid. This happens intermittently, and requires a long-running application to observe. I would expect the platform loginSuccess, loginError, or refreshError event handlers to execute before my code hits my sanity check platform.isValidToken() call...but none of them fire. 

This behavior is troubling for Developers.

Improvement suggestion would be to have the SDK cache the access_token TTL (taking into account the initialization time from the .login() request for latency) and then to begin submitting a request for a new token via the refresh flow at 80% marker of the access_token TTL. This gives the SDK plenty of time to re-request in the event there are errors obtaining a new token, or gives the consuming application an opportunity to be notified and handle the upcoming blockage properly (by requesting the user attempt to re-auth).

**Comment by kirill-konshin** [comment]
If your app does not make any API calls then no events will be fired. This is by design.

SDK already stores access_token TTL and performs refreshes within certain time before expiration.
