### ISSUE TITLE
Can't listen to events

### ISSUE THREAD

**Issue by zeeshanfts** [ringcentral/ringcentral-js#29]
After successful subscription its not listening the events.

**Comment by LingForCC** [comment]
Do all endpoint not work, Or just a specific endpoint? Could you provide the code snippet you use? Thanks!

**Comment by zeeshanfts** [comment]
Here is full code snippets. Please advice
![pic2](https://cloud.githubusercontent.com/assets/6530305/15607748/2d91f302-240d-11e6-8d24-e686dfed7723.png)
![pic1](https://cloud.githubusercontent.com/assets/6530305/15607751/31f6fe6a-240d-11e6-9836-b8c482771367.png)

**Comment by LingForCC** [comment]
Code looks fine. But Sandbox + Presence subscription...Could be a problem with Sandbox environment itself. Could you please do following test for further clarification

- If you have production account, could you please run the same code with it to see whether it works?
- If you don't have production account, could you please test the subscription with endpoint 'message-store'? Just replace `presence` with `message-store` and send a SMS to the phone number to get notification.

**Comment by aahtesham** [comment]
i replace presece with message store now it give **Subscription Error: Parameter [eventFilters] value is invalid**

**Comment by aahtesham** [comment]
my code	
var subscription = rcsdk.createSubscription();
	subscription
   .setEventFilters(['/account/~/extension/~/message-store?detailedTelephonyState=true']) // a list of server-side events
   .register()
   .then(function(response) {
		console.log('Success: Subscription is listening');
	}).catch(function(e) {
	    bootbox.alert('Subscription Error: ' + e.message);
	});
	
	subscription.on(subscription.events.notification, function(msg) {
		_.extend(accountPresence, msg);
		console.log(msg);
	});
	 
	subscription.register().then(function(response) {
	 
	}).catch(function(e) {
	    bootbox.alert('Subscription Error: ' + e.message);
	});
	return subscription;
	
	rcsdk.platform()
    .post('/account/~/extension/~/sms', {
        from: {phoneNumber:'01753376414'}, // Your sms-enabled phone number
        to: [
            {phoneNumber:'+447800656909'} // Second party's phone number
        ],
        text: 'Message content'
    })
    .then(function(response) {
        alert('Success: ' + response.json().id);
    })
    .catch(function(e) {
        alert('Error: ' + e.message);
    });

**Comment by LingForCC** [comment]
My bad. The subscription endpoint should be `'/account/~/extension/~/message-store` without query param.

**Comment by zeeshanfts** [comment]
LingForCC could you also tell me the sending number for message would it be the sandbox number or actual production number. Do we need to enable any setting to send messages in sandbox or its automatically enabled.

**Comment by aahtesham** [comment]
could not send message after doing this '/account/~/extension/~/message-store without query param.

**Comment by LingForCC** [comment]
Check the API Development Guide [here](https://developer.ringcentral.com/api-docs/latest/index.html#!#APIPermissions.html)
You need `SMS` permission for your app to send/receive messages. Basically there is no difference in Sandbox number and production number. You could transmit messages between these two numbers.

**Comment by aahtesham** [comment]
this response is getting when success fully login  
  "scope" : "SMS ReadCallLog ReadAccounts RingOut ReadMessages ReadPresence InternalMessages",

**Comment by aahtesham** [comment]
sms permission is enabled..

**Comment by LingForCC** [comment]
Then you need to check your phone numbers. For number `01753376414`, I suggest you remove the first 0. For number `+447800656909`. I suggest you remove the first `+`. Besides, do you get any error message when sending sms?

**Comment by aahtesham** [comment]
no there is no error message beside this..

**Comment by aahtesham** [comment]
our actual number start with 1573376414 and we are adding country code 44 before this number according  to you our number become  441573376414 a don't get any error but couldnot recieve any message.

**Comment by LingForCC** [comment]
What about the number `01753376414`? It doesn't seem to be a valid number.

**Comment by zeeshanfts** [comment]
It's our local no without country code but when we add country code it would be 441753376414

**Comment by LingForCC** [comment]
Wait...Are these two numbers coming from Developer Portal? Basically you should use the number, which you use to login RC service, to send the message.

**Comment by zeeshanfts** [comment]
No this is the rc no 442037713676 even I have used this one to send message but same result

**Comment by anilkumarbp** [comment]
Hi @zeeshanfts : 

From the comments, i do see there are two issues here : 

1.) Unable to get presence Events 
We are still working on the Sandbox presence Events and if you have further queries, you could open a support case at "devsupport@ringcentral.com"

2.) Unable to send the SMS:
**Solution:** You could check for the list of valid SMS sending numbers here:  
[Retrieving a List of Valid SMS Sending Numbers](http://ringcentral-sdk-ruby.readthedocs.io/en/latest/usage/messages/SMS-Messages/#retrieving-a-list-of-valid-sms-sending-numbers
)

If you have any doubts you could email us at "devsupport@ringcentral.com" addressing the issue as . We could close this issue for now.

**Comment by zeeshanfts** [comment]
Thanks for updating anil. Do you have any deadline for this fix

**Comment by anilkumarbp** [comment]
@zeeshanfts :
We have resolved the issue with the "Presence Events" you should now be able to receive the presence events.

Please consider the issue as closed.

**Comment by zeeshanfts** [comment]
Hi, i  m getting undefined error in response after success full subscription. here attached image.
![542176a2a491959792b9b2fed4f9d7690bb16f87b25165c01a pimgpsh_thumbnail_win_distr](https://cloud.githubusercontent.com/assets/6530305/15704793/19e730ee-27e4-11e6-8893-a5b0d90ce398.jpg)
