### ISSUE TITLE
How to deal with subscription on page refresh?

### ISSUE THREAD

**Issue by u9520107** [ringcentral/ringcentral-js#33]
subscription.remove is an async function, and the request sent is also an async request.
If we use the beforeunload event to try and delete subscriptions, the browser never really send out the request, and we end up with stagnant subscriptions in the server.

What should we be doing to make sure that the subscriptions are cleared before the page refreshes?

**Comment by kirill-konshin** [comment]
There is a Cached Subscription object: https://github.com/ringcentral/ringcentral-js#shorthand, version 3.x has slightly different implementation than 2.x.

**Comment by kirill-konshin** [comment]
And obviously you need to use only one subscription for all event types and then re-route them properly on `notification` event.
