### ISSUE TITLE
fetch TypeError in Chrome using native fetch

### ISSUE THREAD

**Issue by u9520107** [ringcentral/ringcentral-js#35]
I get this error when using native fetch in Chrome:
```
TypeError: Failed to construct 'Request': Request with GET/HEAD method cannot have body.
```

src/http/Client.js#129
```javascript
            if (contentType.indexOf(ApiResponse._jsonContentType) > -1) {
                init.body = JSON.stringify(init.body);
            } else if (contentType.indexOf(ApiResponse._urlencodedContentType) > -1) {
                init.body = queryStringify(init.body);
            }
```
When init.body is null, you're settings init.body = 'null', which result in TypeError when method is 'GET' or 'HEAD'.
I think for GET and HEAD, you should just explicitly set init.body = null here.

**Comment by u9520107** [comment]
src/http/Client.js#118
```javascript
         // Serialize body
         if (isPlainObject(init.body) || !init.body) {
```

Why do you have to serialize body if !init.body?
Are you trying to use !!init.body?

**Comment by kirill-konshin** [comment]
We need to mess with content type only when body is a plain object or there is no body at all. This if is against `FormData`, `Buffer`, `Blob` bodies where either user or `fetch` itself will set appropriate headers.

**Comment by kirill-konshin** [comment]
Fixed in https://github.com/ringcentral/ringcentral-js/pull/36
