### ISSUE TITLE
Subscriptions Fax not returned 

### ISSUE THREAD

**Issue by mgw2007** [ringcentral/ringcentral-js#37]
Hi 
I use this code 

`var subscription = rcsdk.createSubscription();
 subscription.on(subscription.events.notification, function(msg) {
                 console.log(msg, msg.body);
 });
 subscription.setEventFilters(['/account/~/extension/~/message-store']).register()`

To notify user with any new SMS or Fax
The SMS working fine If I send sms to the user the subscription return it but for fax its not working 

Thanks

**Comment by tylerlong** [comment]
Could you please confirm that fax has been received successfully by the user? You can let the user login the RingCentral desktop app to confirm. This is just to make sure that there is no problem in the fax sending code.

**Comment by anilkumarbp** [comment]
Hi @mgw2007 please login into the `RingCentral Desktop` app to confirm this as suggested above by @tylerlong . You would receive a notification event once the fax has been delivered to the extension. Which you would see in the RingCentral Desktop app.

You could also ref to a sample application to set up Subscription here : 
[Set-up-Subscription using RingCentral JS SDK](https://github.com/anilkumarbp/Subscriptions_Generator)

**Comment by mgw2007** [comment]
Hi
The fax is received so I will try  https://github.com/anilkumarbp/Subscriptions_Generator and tell you the result

**Comment by mgw2007** [comment]
Hi
I checked the fax is sent to user email successfully and after I sent It I received the fax id 
But for subscriptions   To notify user with any new SMS or Fax
now both  SMS or Fax is not received even I not change any thing in my code 

I used chrome  for development and I found this url 
[https://ps8.pubnub.com/subscribe/sub-c-b8b9cd8c-e906-11e2-b383-02ee2ddab7fe/724804990937514_e21ae7c2/0/14707802339761336?uuid=a994436c-7932-46f5-945a-131bb577f853&pnsdk=PubNub-JS-Web%2F3.7.23](url)

is take very long time until be aborted

**Comment by kirill-konshin** [comment]
That is a long poll request, it's normal that it is taking long time before abort and reconnect. The weird part is that you don't get notification, because in this case this long poll request should resolve quicker.

**Comment by tylerlong** [comment]
@mgw2007 it sounds like an environment issue. Because you didn't change anything in your code and SMS notification stopped working.

By the way, is your app running in sandbox or production? Sometimes there are issues for notifications in sandbox environment.

**Comment by mgw2007** [comment]
my app running on sand box now
all sms notificaitons I received on email only
but no notifications on the browser until now :(

**Comment by tylerlong** [comment]
Did you try the project https://github.com/anilkumarbp/Subscriptions_Generator as suggested by @anilkumarbp ? That project has been tested and it should work. If it doesn't work, then there must be something wrong with your sandbox environment. If you don't try that first, we are unable to tell if it's a coding issue or env issue.

**Comment by mgw2007** [comment]
Hi
I tried the project https://github.com/anilkumarbp/Subscriptions_Generator  
I create new app with key **mW2Y9tmiROa7PFhNCzLh3w**  and I got the same results no sms notifications but all sms sent to my email successfully and you can check the screenshots
this is the terminal results [https://s10.postimg.org/m1b7o7c3d/subscription.png](url)
this is my email sms messages [https://s9.postimg.org/s8ozocz8v/sms_emails.png](url)

in screen shots you will find a lot of sms emails but in terminal no notifications appear

**Comment by anilkumarbp** [comment]
Hi @mgw2007 , 

We have a known issue at the moment with receiving notification events for `Presence` and `Message-Store`.

Please look out for this space and we would update you once we have the issue fixed.

**Comment by anilkumarbp** [comment]
@mgw2007 ,
The issue seems to be fixed now. Could you please try again and let us know if it is working.

**Comment by mgw2007** [comment]
Thanks @anilkumarbp 
The issue resolved I can now received sms notifications in both server and client side also I received sms on email
But when I try to send fax the sending working fine but I can not receive any notification nor email about the fax 
Is some thing wrong in the fax ? or there is no way to receive notifications about fax?

**Comment by mgw2007** [comment]
Why you close the issue 
can you replay on the main question
To notify user with any new SMS or Fax
The SMS working fine If I send sms to the user the subscription return it but for fax its not working

**Comment by tylerlong** [comment]
> But when I try to send fax the sending working fine but I can not receive any notification nor email about the fax 

So is the fax received by the user or not? Could you please confirm that? I think you will not receive any notifications unless the fax was sent successfully. Please logon the RingCentral desktop app to check if the fax has been received by the user. Here is how you can logon the desktop app with sandbox account: https://developers.ringcentral.com/library/tutorials/test-account.html

**Comment by mgw2007** [comment]
Ok I installed the ringcentral app on windows and I configure the sandbox configs 
so what happened is 
I used this code to send the fax
`                      function sendFax(){

                            var body = {
                                to: [{phoneNumber: targetUser.username}], 
                                faxResolution: 'High',
                            }
                            var formData = new FormData();

                            formData.append('json', new File([JSON.stringify(body)], 'request.json', {type: 'application/json'}));

                            var fileField = document.getElementById('faxFile');

                            for (var i = 0, file; file = fileField.files[i]; ++i) {
                                formData.append('attachment', file); // you can also use file.name instead of 'attachment'
                            }
                            formData.append('attachment', new File(['some plain text'], 'text.txt', {type: 'application/octet-stream'}));

                            rcsdk.platform().post('/account/~/extension/~/fax', formData).then(function(response) {
                                alert('Success: ' + response.json().id);
                            }).catch(function(e) {
                                        alert('Error: ' + e.message);
                                    });
                        }`

The fax is sent and the id returned successfully but on the target user account on softphone he did not receive the fax but he received in call logs tab call log with text Fax Failed as you can see in attached image of target user softphone
![receivedfax](https://cloud.githubusercontent.com/assets/949904/17636240/3deb33ce-60dc-11e6-8eda-99f134ae1834.png)

**Comment by grokify** [comment]
@mgw2007 wrote:
> The fax is sent and the id returned successfully but on the target user account on softphone he did not receive the fax but he received in call logs tab call log with text Fax Failed as you can see in attached image of target user softphone
When the fax API call is posted, the fax is queued but is not sent yet. The response will indicate the id along with the status which is in the `messageStatus` property. Initially, this will say `queued`. Later this will be updated to `Sent` if successful or `Sending Failed` if unsuccessful.

More information is available on the [fax FAQ](http://ringcentral-faq.readthedocs.io/en/latest/fax/).

**Comment by mgw2007** [comment]
@grokify Thanks for your replay
I checked the send fax response and I found that the messageStatus is "Queued"
and after 4 min the target user received the fax but Result "Receive Error" and in call logs Result Description also "Receive Error"

**Comment by grokify** [comment]
@mgw2007

That sounds like the fax receiver is having difficulty receiving the fax.

Can you try sending to another RingCentral number so the recipient is also using RingCentral?

**Comment by mgw2007** [comment]
I try the two numbers on sandbox account and they have same issue
What could be the reason of this issue my be because we you sandbox not real account ?

**Comment by grokify** [comment]
@mgw2007 Can you open a support case or send an email to devsupport@ringcentral.com indicating this along with the sender and recipient phone numbers you are using?
