### ISSUE TITLE
Add Subscription with query string return "Parameter [eventFilters] value is invalid"

### ISSUE THREAD

**Issue by mgw2007** [ringcentral/ringcentral-js#40]
Hi
When I try to add sms subscription  
`subscription.setEventFilters(['/account/~/extension/~/message-store?messageType=SMS']).register()`
its return Parameter [eventFilters] value is invalid

but if I added 
`subscription.setEventFilters(['/account/~/extension/~/message-store']).register()`
its working fine without  messageType=SMS

**Comment by creatovisguru** [comment]
Message Store eventFilters in a subscription are for an extension, your
consuming application code would filter out the desired events based on the
event notification properties.

Benjamin Dean
415.890.5908
@bdeanindy

**Comment by mgw2007** [comment]
Thanks for your replay
But I did not get what you mean

According to https://developer.ringcentral.com/api-docs/latest/index.html#!#RefSubscription.html
'/account/~/extension/~/message-store?messageType=SMS' it should working

Do you mean I use '/account/~/extension/~/message-store' and then filter the response as I need

THanks

**Comment by bdeanindy** [comment]
That was my misunderstanding. I wasn't aware that this type of filtering
was available (need to test this out later). One of our Developer Relations
Engineers, Anil Kumar, just posted a response about this in our developer
community last night. Here is a copy of it...

Yes. This is now possible using the following event filters :

‘/restapi/v1.0/account/~/extension/' + extension_number +
'/message-store/instant?type=SMS’

Consider the following subscription creation request:

POST .../restapi/v1.0/subscription {
    "eventFilters": [
        "/restapi/v1.0/account/~/extension/' + extension_number +
'/message-store/instant?type=SMS”
    ],
    "deliveryMode": {
      "transportType": "PubNub"
    }
}

Benjamin Dean
415.890.5908
@bdeanindy

**Comment by mgw2007** [comment]
yes

`‘/restapi/v1.0/account/~/extension/' + extension_number +
'/message-store/instant?type=SMS’` **working fine**

Thanks

**Comment by mgw2007** [comment]
Hi 
I have another question 

can you check end point 
GET /restapi/v1.0/account/{accountId}/extension/{extensionId}/profile-image

because I tried it using PHP and Js but its always return 404

Thanks

**Comment by mgw2007** [comment]
any help ??

**Comment by kirill-konshin** [comment]
Have you uploaded anything as your profile image?

**Comment by tylerlong** [comment]
@mgw2007 I've tested this endpoint in C# and it does work. I think the root cause is just like @kirill-konshin said you hadn't upload your profile image.

Here is the C# code if you need it:  https://github.com/ringcentral/ringcentral-csharp-client/blob/master/RingCentral.Test/BinaryTest.cs#L21
