### ISSUE TITLE
Subscription Notification is not working, error from ringcentral.js

### ISSUE THREAD

**Issue by azwaralam** [ringcentral/ringcentral-js#41]
Find the attached snapshot. I made a subscription successfully but when i am getting notification then i am getting error from ringcentral.js

![ringcentraljserror](https://cloud.githubusercontent.com/assets/21097847/17764841/82c5041c-653b-11e6-8b42-bdf5255fc49b.png)

**Comment by kirill-konshin** [comment]
This object is a part of PUBNUB. Please show how you embed SDK into the page and provide all other necessary information. What version of SDK do you have?

**Comment by azwaralam** [comment]
Find the attached file is the source code of website project. In this i am using ringcentral-js-master library and on the root there is a page with the name SubscriptionPage.html. In this page you can see i am calling CreatIncomingSubscriptions method for subscription on button click. Subscription is creating successfully but when i am getting notification at that time i am getting the error from ringcentral.js

Please help me out i am stuck on this. Please let me know what i am doing wrong in this,
[WebSite2.zip](https://github.com/ringcentral/ringcentral-js/files/426410/WebSite2.zip)

**Comment by kirill-konshin** [comment]
You are using the outdated version of PUBNUB which does not have `crypto_obj` exposed as expected by SDK. Please use the following version: http://cdn.pubnub.com/pubnub-3.15.2.min.js. Documentation has been updated accordingly.

**Comment by azwaralam** [comment]
ok thanks, i will get back to you after checking this

**Comment by azwaralam** [comment]
Yes it is working thanks man!

**Comment by kirill-konshin** [comment]
You're welcome.

**Comment by azwaralam** [comment]
I am not receiving notification from sandbox? Is there any upgrade going on ?
