### ISSUE TITLE
Subscription Notification from Sandbox Environment

### ISSUE THREAD

**Issue by azwaralam** [ringcentral/ringcentral-js#42]
Hi,

I am not receiving subscription notification from sandbox environment? Is there any upgrade going on ?

**Comment by tylerlong** [comment]
I confirm that it's not working at the moment.  Subscription notification from sandbox environment stops working from time to time.  You can send email to platform@ringcentral.com to report this issue.

**Comment by azwaralam** [comment]
thank you for the confirmation

**Comment by anilkumarbp** [comment]
Hi @azwaralam 

The Subscription Events are now working fine for : 
- `SMS`
- `Voice Calls`
