### ISSUE TITLE
Isomorphic-fetch

### ISSUE THREAD

**Issue by u9520107** [ringcentral/ringcentral-js#46]
Do you think we can replace the node-fetch/whatwg-fetch dependencies with isomorphic-fetch?
It's fundamentally the same thing as using node-fetch and whatwg-fetch on appropriate moments, but this way we don't have to alias node-fetch to whatwg-fetch in the webpack.config for our applications.

**Comment by kirill-konshin** [comment]
Sure.

**Comment by kirill-konshin** [comment]
Implemented in `feature/universal-fetch` branch. Feel free to try.

Since `PUBNUB` now also has `browser` and `main` declarations in `package.json` aliases are no longer needed.
