### ISSUE TITLE
Receiving npm warnings on install

### ISSUE THREAD

**Issue by bdeanindy** [ringcentral/ringcentral-js#5]
npm WARN deprecated npmconf@2.1.1: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN engine agentkeepalive@0.2.4: wanted: {"node":"0.10.x"} (current: {"node":"4.1.0","npm":"2.14.3"})
npm WARN deprecated lodash@1.0.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0

**Comment by kirill-konshin** [comment]
We cannot control subsequent dependencies of packages that we use. Please report those errors to original package maintainers.
