### ISSUE TITLE
[RingOut] - Use Super Admin Credentials for an entire account

### ISSUE THREAD

**Issue by blak3r2** [ringcentral/ringcentral-js#50]
As a RingCentral App Administrator that desires "click to call" functionality, I do not want to make each of my end users have to enter their RC username/password or perform an oauth step just to be able to do click to dial.  I would like to be able to use a single set of credentials like I am able to for receiving the phone event subscription events.

I would like to be able to perform at Ringout api request authenticated as one of the super admins and specify the To/From fields the same way.
### Technical Description

The RingOut API requires authentication by the individual who is placing the click to call.  I believe if you do not do this the phone events come in such that they're an inbound call as opposed to an outbound call. I'm not positive on what exactly the limitation is... but this was confirmed in the past by devsupport.

**Comment by tylerlong** [comment]
I think what you want to do is viable with RingCentral API. Have you encountered any issues?

I am not sure if I have fully understood your requirements. But in RingCentral terminology, `RingOut` is not the same as `make a phone call`. RingOut means connecting two numbers so they could talk. And those two numbers don't have to be RingCentral numbers at all. So which RingCentral account you use to obtain credentials doesn't matter as long as the account has `RingOut` permission.

**Comment by blak3r2** [comment]
Thanks @tylerlong 

The issue is specific to when you're using RingOut AND also using the event subscription API at the same time to track and log call events (like in a CRM Integration). You are absolutely correct that you can dial any number with the admin credentials.  The problem becomes the phone events that then come out are overridden with the extension of the user who performed the request.

Note: I might not be using perfect RC vernacular.  When i'm saying x101's credentials i mean the user account who is using the device associated with x101.  


**x101 Credentials --> Ringout -- which dials --> a DID associated with x102 in first leg**
When x101's credentials  are used to generate the access token which are used in the RingOut API Rest Call and you enter a ```from``` number which is the RingCentral phone number associated with x102.  Then, when you receive call events through the pubnub subscription.  The extension that presented in the call event is the extension identifier for x101 (but you actually answered it on x102).

![image](https://cloud.githubusercontent.com/assets/10790899/19294291/b8cee02a-8ff0-11e6-9410-368a74d41c46.png)


**x102 Credentials --> Ringout which dials the same number**
![image](https://cloud.githubusercontent.com/assets/10790899/19294387/a9486788-8ff1-11e6-8224-43f8b14ac03d.png)


## Recommendation
![image](https://cloud.githubusercontent.com/assets/10790899/19294455/6c9f6ad8-8ff2-11e6-88c9-10d90cb053d6.png)

Essentially in a CRM Integration, you need to link an RC Extension with a CRM User Account.  So, calls that happen in RC are logged to the appropriate CRM user. Our application differs from the RC Salesforce application in that we do not do any client side (in browser) logging on the user level.  We have a server to server connection which maintains an event channel for the entire organization. Therefore, we do not require each user to authenticate in order to log phone events for them.  We only need user level credentials or tokens for the purpose of Click To Dial in the case that a user is not using a softphone.  



# Additional Stuff

### Code for good measure

```javascript
    // self.authenticate just performs a platform.login request passing username/password
    self.authenticate(authOpts, function (err, response) {
        if (err) {
            return promise.reject( new Errors.CtdInvalidExtensionCredentials('Invalid Ringcentral Username or Password', err.apiResponse));
        }

        var accessToken = _.get(response, 'access_token');
        var ringOutOpts = {
            method: 'POST',
            url: 'https://platform.ringcentral.com/restapi/v1.0/account/~/extension/~/ringout',
            json: true,
            headers: {
                'Authorization': 'Bearer ' + accessToken
            },
            body: {
                from: {phoneNumber: originateFrom},
                to: {phoneNumber: phoneNumber},
            }
        };

        request(ringOutOpts, function (err, response) {
            if (err) {
                return promise.reject(new Errors.CtdErrorGeneric(err,response) );
            } else if( response.statusCode !== 200 ) {
                return promise.reject( new Errors.CtdErrorGeneric(_.get(response, "body.message"), response) );
            }
            return promise.resolve('Accepted By Ringcentral');
    }


RCNativeAdaptor.prototype.authenticate = function (opts, callback) {
    var self = this;

    if (typeof opts === 'function') {
        callback = opts;
    }
    self.platform.login({
        username: opts.username || this.config.username, // phone number in full format
        password: opts.password || this.config.password,
        extension: opts.extension     // ok for this to not be defined.
    }).then(function (response) {
        return callback(null, response.json());
    }).catch(function (err) {
        return callback(err);
    });
};
```

## x101
![image](https://cloud.githubusercontent.com/assets/10790899/19294508/ecddea44-8ff2-11e6-9a19-258722dd9fc1.png)


## x102
![image](https://cloud.githubusercontent.com/assets/10790899/19294486/bf8befdc-8ff2-11e6-92be-52a9a335cdf9.png)

**Comment by tylerlong** [comment]
Thank you for the detailed information. I am not an expert on this issue but I am sure someone else is able to answer it.

A quick question: in your `recommendation` part, you want to set extension id in the URL. Have you tried that?  You can replace `~` with a specific extension ID.

**Comment by blak3r2** [comment]
Yes, I tried it again tonight. I believe it was just ignored and had the same behavior.

**Comment by LingForCC** [comment]
@blak3r2 I am afraid that our backend doesn't support this endpoint for RingOut for now. I guess you could use 'account/~/extension' and 'account/~/phone-number' to cross-reference and get extension info.

**Comment by blak3r2** [comment]
@LingForCC 

Are you suggesting that rather then my app relying on ```extensionId``` only for mapping calls to users... That we treat Outbound calls where ```extensionId``` === the "Auth User's" extensionId... then use the ```from``` number to determine the user?

**Comment by LingForCC** [comment]
@blak3r2 

More or less I think. First of all, once your app starts, it needs use 'account/~/extension' and 'account/~/phone-number' to setup a data structure of extensions and corresponding phone numbers. Then you can match the phone number in PubNub notification(from number for Outbound call or to number for Inbound call) to find extension info based on aforementioned lookup table.

But noticed that since the extension list and phone number list can be configured in Service Web. You app may need to update the info in regular timespan to ensure the data is updated.

**Comment by blak3r2** [comment]
@LingForCC 

That's an option I suppose but it's not ideal.  It would require processing of phone events differently for outbound cases than all other cases... which isn't as simple as just adding an if statement as in our case at least... we have a separation of concerns in that the phone system processor essentially sets a common call model and populates the extensionId.  A separate part of the code base is responsible for mapping the extension to an appropriate user object.  

I imagine a serious of edge cases would also crop up as a result of transfers.  

Can you all please discuss adding something like this at the next developer meeting?

**Comment by LingForCC** [comment]
@blak3r2 

Sure. I already mention this issue to our PM and we will have some discussions on this soon. Thanks for your feedback!

Have you tried https://devcommunity.ringcentral.com/? That is the official forum for new feature request for RingCentral Platform. You could also ask general target problem there.

**Comment by LCradz** [comment]
FYI. A year later and there is still no option to use extensionID in their API as a super admin to call out for any extension.

This is actually the reason I'm working with this Javascript SDK instead of the C# one I was building a server side only app.
