### ISSUE TITLE
Call Queues need to be more powerful -or- Event Subscriptions need to better track extensionId through callForwarding.

### ISSUE THREAD

**Issue by blak3r2** [ringcentral/ringcentral-js#51]
As a user, I prefer to use Call Forwarding / Ring Groups as I have more control over how calls are sent to our users.  I can't however, because my CRM Call Logging application built on top of the RCSDK only works properly with Call Queues.  I'd either like Call Queues to be more powerful or perhaps their is a way to make the event api work with RingGroups.
## Technical Issue

With Call Forwarding Rules, all the phones that are "forwarded to" still present themselves via the pubnub phone event subscriptions as if it was the parent extension of the group. This feature was essentially designed to allow an end user to add a cell phone number and have it ring through to that users device.  In this case it's entirely appropriate to present the calls as if it was coming in on the parent extension.   But, it creates an issue when users create a setup such as the one shown below:

```
New Call ---> x167 ----> Group A  --> x101, x102, x103
                   ----> Group B  --> x201, x202, x203
```

It doesn't matter if the call is answered by x101, x102, x103, x201, x202, or x203... the `extensionId` that comes in via the event subscription will have the identifier for x167.  

The workaround advised by RC Dev Support was then to use Call Queues. Call Queues properly present the extensionId of the person who answers the call which is good... as we can then properly relate calls to the appropriate user.  The problem is then a business process issue.  The customer cannot replicate the same functionality they had in call queues.
### Example setup they cannot replicate

Call would go to the first group for 25s, then and only then would it ring the second group.

![image](https://cloud.githubusercontent.com/assets/10790899/19295139/178dbfc6-8ff8-11e6-8f3a-d22cd6abe061.png)

![image](https://cloud.githubusercontent.com/assets/10790899/19295144/1d0145f4-8ff8-11e6-8ff7-fca37d1aae8f.png)

**Comment by LingForCC** [comment]
@blak3r2  As suggested by our DevSupport, this is a limitation of our Platform API. I will forward this to our internal system as a new feature request.

@grokify Do you have any suggestion on this?

**Comment by kirill-konshin** [comment]
Closing due to inactvity
