### ISSUE TITLE
Subscription renew should handle 404 status code properly

### ISSUE THREAD

**Issue by tylerlong** [ringcentral/ringcentral-js#52]
The subscription might have expired at the time your do renewal.  There are several possible reasons: 

1. you computer went to sleep and subscription expired before you computer wake up.
1. there was network issue you failed to do renew on time and subscription expired.
1. ...

In such case, server will return 404 status code with error code "CMN-102" and error message "Resource for parameter [subscriptionId] is not found".

We should handle this exception automatically and don't bother programmers. We can do a new subscription if renewal failed due to 404 not found.

Sample code in Swift: https://github.com/tylerlong/ringcentral-swift-client/blob/1db6ddfb74a59c42484eece81ea2b24fda99a9af/Source/SubscriptionService.swift#L98

**Comment by kirill-konshin** [comment]
Per SDK philosophy (granular and minimalistic reusable methods) it should not do anything on users behalf if application logic may be involved.

As mentioned in #70 new events were added so you can capture `automaticRenewError` and do whatever you want with your subscription. For example call `resubscribe()` method. New events will be released in 3.1.2.
