### ISSUE TITLE
throwing refreshError on loggedIn check when user is not logged in

### ISSUE THREAD

**Issue by u9520107** [ringcentral/ringcentral-js#53]
Currently, if there is no access token present, when we try to check loggedIn status with loggedIn function, Platform would emit a refreshError event. Shouldn't this event only be fired when there was an access token, but there is an error when refreshing the token?

If there is no access token to begin with, we shouldn't even try to do a refresh right?

**Comment by kirill-konshin** [comment]
If there is no access token, sdk tries to refresh, sees that there is no refresh token and emits the error.
