### ISSUE TITLE
The client is unauthorized for the required grant type: [IMPLICIT]

### ISSUE THREAD

**Issue by srigottipati** [ringcentral/ringcentral-js#54]
Following code i am trying to execute under http://localhost:8888/#RingCentral URL.

var rcsdk;
function initRingCentralSDK(appKey,appSecret)
{
	rcsdk = new RingCentral.SDK({
    server: RingCentral.SDK.server.sandbox,
//  server: RingCentral.SDK.server.production,
    appKey: appKey,
    appSecret: appSecret,
    redirectUri: 'http://localhost:8888/#RingCentralRedirect' // optional
	});
	var platform = rcsdk.platform();
	var loginUrl = platform.loginUrl({implicit: true}); // implicit parameter is optional, default false
	platform
    .loginWindow({url: loginUrl}) // this method also allows to supply more options to control window position
    .then(function (loginOptions){
        return platform.login(loginOptions);
    })
    
}

and in developer.ringcentral.com's app's oAuth Settings,following are provided under OAuth Redirect URI

http://localhost:8888/#RingCentralRedirect
http://localhost:8888/#RingCentral

but getting following error,

http://localhost:8888/#error=unauthorized_client&error_description=The+client+is+unauthorized+for+the+required+grant+type:+%5BIMPLICIT%5D

any suggestions to resolve the issue?

Thank you very much in advance

Sri

**Comment by srigottipati** [comment]
I am trying to implement code provided under "Popup Setup" of "3-legged OAuth 2.0 Flows".
Am I missing any thing?

**Comment by tylerlong** [comment]
It probably means your app doesn't support authorization code flow. Please check the screenshot below:
https://github.com/ringcentral/ringcentral-php/issues/39#issuecomment-242907546

But instead of looking for "password flow", you should look for "authorization code".

**Comment by srigottipati** [comment]
thanks tylerlong for your suggestion and issue is resolved.

Now ,after "Authorise" button is clicked,i am getting following error URL,

http://localhost:8888/#RingCentralRedirect?error=invalid_request&error_description=CMN-101:Parameter [redirectUri] value is invalid

where as,

"http://localhost:8888/#RingCentralRedirect" is the redirect URL provided by my code.

**Comment by LingForCC** [comment]
@srigottipati  Try to remove '#' from your redirectUri. Use something like 'http://localhost:8888/redirect.html'.

**Comment by srigottipati** [comment]
thanks @LingForCC.
