### ISSUE TITLE
Call log based on called number

### ISSUE THREAD

**Issue by srigottipati** [ringcentral/ringcentral-js#56]
i am trying to retrieve call log based on called number,following is my code.

        var a = rc_helpers.call();
        rc_platform.send({
            url: a.createUrl({
                active: !0
            }),
            async: 1,
            method: "GET",
            headers: {},
            query: {
                dateFrom: acRCObject.getDateinyyyymmdd(),
                page: page,
                perPage: perPage
            }
        }).then(function(e) {
            rc_renderlogs(e.json().records)
        })

but no records are being returned.

i am trying to retrieve call logs by pagination.

any suggestions?

thanks in advance.

**Comment by kirill-konshin** [comment]
This space is used for SDK issues, for general support please use devsupport@ringcentral.com, also please provide full request & response from API along with your code.
