### ISSUE TITLE
Is it secure to use app secret when login by JavaScript to add subscriptions?

### ISSUE THREAD

**Issue by mgw2007** [ringcentral/ringcentral-js#57]
Hi
I try to add subscriptions on Fax and SMS
but I found that the user can view the page source and see the App Key and App Secret 
so Is it secure ?

**Comment by tylerlong** [comment]
I don't think it's secure. Client side users can get your app key and app secret if they want to.

However, you account is still safe as long as you don't reveal your password. App key and app secret cannot do anything without authorization with an account and password.

**Comment by grokify** [comment]
Apps should not expose the app secret to end users, e.g. via View Page Source.

There are two general ways to do this with client-facing apps:

1. Apps that are 100% client-side should use the OAuth 2.0 Implicit Grant flow which does not use App Secret. For more information see the [SDK README.md Login section](https://github.com/ringcentral/ringcentral-js#login).
2. Apps that have a server-side component can use the OAuth 2.0 Authorization Grant flow which does use the App Secret but should be handled on the server-side. This is also described in the [SDK README.md Login section](https://github.com/ringcentral/ringcentral-js#login).
