### ISSUE TITLE
Subscription notification event is returning undefined.

### ISSUE THREAD

**Issue by srigottipati** [ringcentral/ringcentral-js#58]
Hello There,

I am trying to implement subscription for event notifications .

following is the code,

```javascript
acRCObject.subscribeWithRC = function() {

    console.log("Going to subscribe with ringcentral");
    presenceSubscription = rc_rcsdk.createSubscription({
        detailed: !0
    });
    presenceSubscription.on(presenceSubscription.events.notification, function(response) {
        if (!response) {
            return
        }
        var c = response.body.activeCalls;
     }
```

problem is, when i am testing inbound call, above "response"  argument of subscription notification is being returned as undefined.

when i debugged the code in ring central-bundle.js,following code is failing.

`this.emit(this.events.notification, this._decrypt(message));`

and 

this._decrypt(message) is returning undefined and message value is

`"XXXXXXXXXXXXXXXXXXXXXXXXXX=" (encrypted message)`

and i am using following files of RingCentral,

* sip-0.7.5.js
* ringcentral-bundle.js
* ringcentral-helpers.js
* ringcentral-web-phone.js

and following is the additional code to initiate SDK,

```javascript
acRCObject.loadRingCentralSDK =function ()
{
    if(rc_rcsdk!=null ) return;
    var appKey="XXXXXXXXXX"
    var appSecret="XXXXXXXX"
    if(rc_rcsdk!=null && rc_platform!=null) return;

    rc_rcsdk = new RingCentral.SDK({
    server: RingCentral.SDK.server.sandbox
    });
    rc_platform = rc_rcsdk.platform();
        rc_platform._appKey=appKey;
        rc_platform._appSecret=appSecret;
        rc_helpers=RingCentral.Helpers;    
}
```

any help will be appreciated.

Thanks,

**Comment by tylerlong** [comment]
Interesting, it seems that decryption code is not working properly. We never heard of similar issues before.

Which version of the ringcentral-js library are you using? Can you reproduce this issue constantly?

**Comment by srigottipati** [comment]
hi tylerlong,

thanks for the reply and issue is consistent.

and SDK version is 2.0.6

thanks for help.

sri

**Comment by tylerlong** [comment]
I have no idea of the root cause. You are using the production version of the SDK and it is said to be quite stable.

You can send sample code to devsupport@ringcentral.com for further investigation. Do include this issue link in your email.

**Comment by Daymannovaes** [comment]
What was the resolution of this case? This issue is still open, it got fixed?

I'm also experiencing this issue

**Comment by kirill-konshin** [comment]
@Daymannovaes currently we are not aware of any issues with subscriptions and JS SDK, so as @tylerlong said, please send sample code along with a link to this issue to devsupport@ringcentral.com

**Comment by kirill-konshin** [comment]
If the issue will be reproduced I will reopen it
