### ISSUE TITLE
Error running within a Chrome App

### ISSUE THREAD

**Issue by grokify** [ringcentral/ringcentral-js#6]
When running in a Chrome App, the following error is encountered. Is it possible to update the SDK so it can run in a Chrome App?

```
Uncaught EvalError: Refused to evaluate a string as JavaScript because
'unsafe-eval' is not an allowed source of script in the following Content
Security Policy directive: "script-src 'self' blob: filesystem:
chrome-extension-resource:". ringcentral.js 1068
```
<img width="1258" alt="ringcentral-js_error-chrome-app" src="https://cloud.githubusercontent.com/assets/209872/12865798/a9d3bc9c-cc6b-11e5-8fa0-4068a7d265b8.png">

**Comment by kirill-konshin** [comment]
This one is easy to fix, expect an updated version in the next few days.

**Comment by grokify** [comment]
@kirill-konshin Sounds good. This will be very useful.

**Comment by kirill-konshin** [comment]
I have pushed an update to develop branch, can you check.
