### ISSUE TITLE
Show/ Download fax attachments

### ISSUE THREAD

**Issue by mgw2007** [ringcentral/ringcentral-js#65]
hi
I am trying to retrieve the fax file attachments but I can not extract the binary data from response

**Comment by tylerlong** [comment]
Please post the code you have tried together with the error message.

**Comment by mgw2007** [comment]
there is no error message 
the problem I can not read the binary data from the ApiResponse
no method return the binary data text

platform.get('/restapi/v1.0/account/~/extension/~/message-store/FAXID/content/ATTACHMENTID').then(function(res){console.log(res)})

![screenshot from 2017-02-27 05 26 58](https://cloud.githubusercontent.com/assets/949904/23347802/7ec116f8-fcad-11e6-8997-27e36a1163b1.png)

**Comment by kirill-konshin** [comment]
You can't download binary data via platform.get(), instead you can use any function you like (fetch, XHR, Node's http) with the URL of your attachment processed by platform.buildUrl function.

**Comment by mgw2007** [comment]
thanks
I used PHP and it working fine
