### ISSUE TITLE
Subscription fails to work on internet disconnection and reconnection

### ISSUE THREAD

**Issue by shripathee** [ringcentral/ringcentral-js#79]
We use server-side subscriptions to get the list of active calls. When the internet connection is not available for some time and then it is regained, the subscription fails to work and the events are not received anymore.

**Comment by shripathee** [comment]
Also, the event handlers for **subscription.events.renewError** and **subscription.events.automaticRenewError** are not getting invoked at all when the issue happens.

**Comment by kirill-konshin** [comment]
Looks like PUBNUB does not restore the connection. I will look into this issue.

Btw, in general we recommend to use web hooks for server-side subscriptions.

**Comment by embbnux** [comment]
In browser, this problem happen again. When network is back online, app can not get any notifications.  Hope it will be resolved quickly.

**Comment by kirill-konshin** [comment]
Is this fixed now @embbnux? Your PR should have addressed this, right?

**Comment by embbnux** [comment]
@kirill-konshin Yes, fixed in 3.x
