### ISSUE TITLE
3-legged OAuth Popup doesn't redirect in Internet Explorer 11

### ISSUE THREAD

**Issue by LCradz** [ringcentral/ringcentral-js#90]
https://whatsmybrowser.org/b/YVQ25MA

Using the demo provided out of the box it works fine in Chrome but in Internet Explorer 11 after clicking Implicit Grant on the demo/login.html page and logging in to RingCentral and authorizing the app it goes to a blank page (the demo/oauth/redirect.html page) and sits there. No error shown in F12 Developer Tools.

**Comment by anilkumarbp** [comment]
@LCradz ,

So I tested the [RingCentral-Js-Demo](https://github.com/ringcentral/ringcentral-js/tree/master/demo) on a Windows machine + IE 11.1593.14393.0

**BrowserDetails**
https://whatsmybrowser.org/b/R65C49K

In-order to test the 3Legged OAuth PopUp feature, I just followed the simple steps below: 

1. git clone https://github.com/ringcentral/ringcentral-js.git             ( `you might need to install git on windows if you do not have it`)

1. install http-server using npm ( npm install -g http-server )           ( `you might need to install npm on windows if you do not have it`)

1. `cd ringcentral-js`

1. `http-server`

Below is the screenshot of the Demo working successfully on Windows + IE11 : 
![screen shot 2017-10-31 at 2 26 38 pm](https://user-images.githubusercontent.com/5293126/32250149-9f781466-be48-11e7-84a3-4b2ede75a083.png)

Could you please make sure you follow the same procedure to test if the [Demo](https://github.com/ringcentral/ringcentral-js/tree/master/demo)  works?

**Comment by LCradz** [comment]
Yea I'm not going to go through all that procedure to test.

My end users have problems with it and I couldn't recreate either for a period of time. It's like the refresh token or something is being cached or expiring or something.

This is getting so frustrating as I get you can't recreate but there is a problem and it's really pissing off my end users who are now not happy we moved to RingCentral due to this one issue.

**Comment by LCradz** [comment]
So I just tried again on my IE and now it works... 

I give up... we're probably just going to have to use another provider instead as this is getting ridiculous.

**Comment by kirill-konshin** [comment]
Is there anything else how we can assist on our end?

**Comment by u9520107** [comment]
@kirill-konshin Although it is not clear to me what exactly went wrong with their setup, but we've seen similar issues with redirect.html getting stuck.
Our suspicion is that if the browser caches the redirect, or if the server hosting the redirect return a 304, the code on the redirect page will not be executed, even though the browser has a cached version of the code. Maybe we should leave a comment or a reminder in the sample redirect.html to advise developers to disable any browser caching for the redirect page, or use the state to pass a time based token to prevent caching to avoid this issue?

**Comment by LCradz** [comment]
@u9520107 that's very interesting actually as I did change the redirect.html page to change the  RingCentral.js reference back to the local version from the CDN version so I could put in some logging code to try to trace this... sure enough after I did that I was able to log on so I gave up and shut down for the day thinking wtf!

I'll test and see.

**Comment by LCradz** [comment]
Thanks Jack!

I think that's it. I added:

` <meta http-equiv="Pragma" content="no-cache">
    <meta http-equiv="Expires" content="-1">`

Now my redirect.html page is returning 200 and I can log on just fine with IE.

**Comment by kirill-konshin** [comment]
Awesome! Guys, PR is very welcome.

**Comment by LCradz** [comment]
Well it did seem to fix my issue last night and this morning I was able to log on again but then later I can't and one of my end users still has the issue while another does not.

So.. question regarding implicit authorization.. do I need to have the app key and app secret when authorizing this way? I seem to remember reading some where not to include app secret but if I don't then the demo forces me to include it. I wonder if that's part of the problem here.

**Comment by kirill-konshin** [comment]
For implicit grant you need only app key.

**Comment by kirill-konshin** [comment]
I suggest to disable caching on server side too.

**Comment by LCradz** [comment]
Disabled all caching on server side and still no joy.

Even manually deleted all ringcentral related cookies and files from end user and still doesn't work.

Would providing the secret affect anything?

Is there a simple example of using iframes instead of this popup and notify other window to refresh via javascript method?

I'm not a JavaScript guru and the only reason I'm using this SDK is to work around the problem of not being able to RingOut via the C# SDK using SuperAdmin and another users extensionID.

**Comment by kirill-konshin** [comment]
IFRAMEs should not be used because RC auth pages have restriction to be opened only as popups for security reasons.

You can open login page not as popup but in top frame https://github.com/ringcentral/ringcentral-js#top-frame-setup

In this case your redirect page should be your main app.

**Comment by kirill-konshin** [comment]
Btw, you can use any 2 phone numbers for RingOut, even not belonging to account, so if your extensions have direct numbers, you can make ringout from super admin using those direct numbers and any other numbers.

**Comment by LCradz** [comment]
Yes but logs show my extentionID not the user who actually created the call.

**Comment by LCradz** [comment]
I also can't set callerID outbound to their direct number unless I use our main number

**Comment by kirill-konshin** [comment]
User, who actually created a call, is your super admin in this case. AFAIK, super admins cannot place calls on behalf of other users.

Please try top frame solution, with disabled cache it should work for you, bc maybe something in user setup prevent cross-window communication, and top frame method is simpler.

**Comment by LCradz** [comment]
No exactly that's the problem. I wanted to do this ALL server side only due to these very problems I have with end users. I don't have control over their setup.

Works great in Chrome but not IE. Very frustrating for me and my end users.

**Comment by LCradz** [comment]
I will try the top frame version.. reason i was asking if there was a demo already built.

**Comment by kirill-konshin** [comment]
I totally understand the frustration. It could also be an interference of extensions/plugins/network config etc.

I suggest to open a ticket using devsupport@ringcentral.com, bc here we address JS SDK related issues, seems that SDK works fine, setup-related questions should be resolved by Dev Support.

You can authorize & make calls from your C# server (w/o JS SDK at all), this is a simple OAuth Authorization Code flow:

1. in dev portal set redirect to server-generated page
2. on your server create an auth page that will redirect to RC auth with `client_id=appKey` and `response_type=code`
3. when redirect page is reached on your server exchange code from params on new pair of tokens using `authorization_code` grant
4. store access & refresh tokens in server session or elsewhere
5. do server-side requests on behalf of actual extensions using their own access tokens

I believe part of these items can be addressed by C# SDK.

P.S. @u9520107 PR with no-cache header is welcome.

**Comment by LCradz** [comment]
Thanks Kirill.

At this point I'll go back to the C# version and build what you suggest. I was trying to save development time by using this JavaScript SDK as it had what I needed out of the box with the demo examples but something isn't playing nice with IE and in the long run I've spent way too much time trying to get this to work.

**Comment by grokify** [comment]
We have the [`ringcentral-demos-oauth`](https://github.com/ringcentral/ringcentral-demos-oauth) repo which has Authorization Code examples for C#, JS and other languages. These demos use JS to open the OAuth popup and then poll the URL of that popup to know when to close it.

Here's the C# example:

https://github.com/ringcentral/ringcentral-demos-oauth/tree/master/csharp-nancy

For the client-side JS implementation, this approach may address the issue of redirect.html not executing because there is no longer any required code there.

* Parent window (launches OAuth popup): https://github.com/ringcentral/ringcentral-demos-oauth/blob/master/javascript/public/index.html
* Redirect URL: https://github.com/ringcentral/ringcentral-demos-oauth/blob/master/javascript/public/callback.html

**Comment by LCradz** [comment]
Thanks grokify

http://ringcentral-csharp.readthedocs.io/en/latest/usage/authorization/Authorization/ gave me exactly what I needed.

I wish your sales people were as responsive as all you guys are. ;) Appreciate all the help.

**Comment by grokify** [comment]
Hi @LCradz,

We have two C# SDKs. The link you posted is for using our older C# SDK which does not have model classes. The new SDK does have model classes and is our future direction.

* New C# SDK: https://github.com/ringcentral/ringcentral-csharp-client
* Old C# SDK: https://github.com/ringcentral/ringcentral-csharp

Here are links to the same methods using the newer SDK:

https://github.com/ringcentral/ringcentral-demos-oauth/blob/master/csharp-nancy/csharp-client-nancy/Program.cs#L37

https://github.com/ringcentral/ringcentral-demos-oauth/blob/master/csharp-nancy/csharp-client-nancy/Program.cs#L54
