### ISSUE TITLE
Http 400 - Unauthorized for this grant type

### ISSUE THREAD

**Issue by RobertRajcool** [ringcentral/ringcentral-js#91]
Hi all I'm try to connect authencation in ringcentral
Getting Http 400(Bad Request) - Unauthorized for this grant type

       var SDK = require('ringcentral');
       var rcsdk = new SDK({ 
           server: SDK.server.sandbox, 
           appKey: 'xxx',
           appSecret: 'xxx',
           redirectUri: ''
       });
       rcsdk.platform()
       .login({
           username: 'xxx', // phone number in full format
           extension: 101, // leave blank if direct number is used
           password: 'xxx'
       })
       .then(function(response) {
           console.log(response)
       })
       .catch(function(e) {
           console.log(e.message  || 'Server cannot authorize user');
       });

**Comment by kirill-konshin** [comment]
/!\ Never post any credentials on GitHub

Your application does not have password grant, use 3-legged OAauth flows instead: implicit or code grant.
