### ISSUE TITLE
Major / breaking changes for JS SDK 4.0

### ISSUE THREAD

**Issue by tylerlong** [ringcentral/ringcentral-js#97]
Here we list all of the major / breaking changes planed for JS SDK 4.0:

1. remove magic endpoint prefix. In previous versions, endpoints such as `/account/~` will be prefixed with `/restapi/v1.0` magically.  In 4.0, we do not do it any more. Users are required to specify the full endpoint.
2. Pubnub was moved to separate package

**Comment by tylerlong** [comment]
Another improvements I want to propose is: 

To abstract away the differences between sending fax in browser and in node. 

I see in the readme file, in order to send a fax, developer needs to write different code for browser and node.

**Comment by kirill-konshin** [comment]
Added #68 — async Cache

**Comment by kirill-konshin** [comment]
Closing, all of that is mentioned in #102 and in changelog.
